### ISSUE TITLE
Configuration file format should have a follow zoom option

### ISSUE THREAD

**Issue by Noitarud** [phyphox/phyphox-android#28]
I open acceleration with g and run for seven seconds, pause, set 'follow new data' on all graphs and save state. Coming back the last step was not recorded. (This helps keep all future recordings on the same scale, reduces set up time since I may not always like to see the squeeze view)

**Comment by Staacks** [comment]
I think this is more a problem of the term "state". We never intended to store the current vizualization (Zoom level, follow state, log axis, active tab etc.), but the "state" is the current experiment configuration with all measured data. Not sure what a good word be to make that distinction, though.

However, I will note on my todo that I should add an attribute to our file format to preselect the "follow" option, so in the future you would be able to create a configuration with this option active. (I'll change the title of this issue accordingly.)
