### ISSUE TITLE
Wired remote

### ISSUE THREAD

**Issue by Noitarud** [phyphox/phyphox-android#69]
Reference circuit:
![linkO](https://github.com/phyphox/phyphox-android/assets/98794719/74dde78b-f501-4691-8680-0282f279904c)

Use headphone buttons to initialise/adjust/switch experiment (also could configure their action in custom experiment) - I don't know if there are more resistance levels for more switches. Android can read double tap as a next track command. Android lock state can cause intermittant or no action (be sure to test on all versions, I have troubles with my players). 

If your setup has a light sensor you could communicate with varying intensities…

**Comment by Staacks** [comment]
_First of all, thanks for all your input. I have seen a few from you pop up in my mail over the weekend and will now answer them all. However, please understand that I will be closing a few of them as this issue tracker (while not really well maintained to begin with) is more for issues (i.e. bugs, crashes, problems) and not that much about feature requests. We have a very long internal list of features that would be nice to have, but limited development capacities, so we usually decide based on how many users would benefit from something and the forums at https://phyphox.org/forums/ might be a much better place with more active users supporting a request or having additional input. I will also copy this block in italics to some of the issues that I close, so others who stumble upon them can read this, too._

I have seen a similar suggestion before and it seems like a clever solution at first. However, this is detected on an OS level and typically bound to audio players. It might be easy to implement (a quick search told me that it actually shows up as a key press event), but I suspect that players can interfere with it. Also, your question implies that you want to use it to control phyphox while the screen is locked and that is an entirely different story. This requires a massive rewrite of large parts of phyphox which need to be formed into a system service, which has been on our todo list for a very long time and will probably be there for a bit longer as it is a massive task.

In terms of relevance of this feature I see two reasons, not to tackle it at the moment:
- Fewer phones even have a headphone jack today and as much as I would like it to come back, it does not look like it will be any time soon. For us this means that this will not be a feature widely used in class, but for individual experiments.
- For such individual experiments we offer our "remote access" feature, which should work on every device and in most scenarios with barely additional setup as long as there is any other device available on the same local network. It is also far superior as it allows direct supervision of the data and even direct download of the results.

So, please understand that while I see this as a "would be nice" feature, I do not think that we will invest development time into this unless someone donates a few extra developers and we run out of other things to implement :)

(Closing as a feature request that is unlikely to be implemented.)

**Comment by Noitarud** [comment]
I cannot remember your policy. Why not create a new option in the issue select page and put it in brief on the entry's caption?

This person has multiple categories:
![Screenshot_20240716-173915](https://github.com/user-attachments/assets/96af379e-5793-4192-8105-b9d4f1d5d47e)
